services:
  frontend:
    build: .
    networks:
      - default
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.forge.rule=Host(`forge.jewellcore.com`)
      - traefik.http.routers.forge.entrypoints=http
      - traefik.http.services.forge.loadbalancer.server.port=80
    restart: unless-stopped

networks:
  coolify:
    external: true
